[build]
  publish = "."

# Form notifications - emails will be sent to these addresses
[[forms]]
  name = "contact"
  
[[forms]]
  name = "demo-request"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"